article/urls.py
from django.contrib import admin
from django.urls import path

from article import views

app_name = "article"
 

urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addArticle, name = "addarticle"),
    path('article/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('',views.showArticles,name = "articles"),
    path('comment/<int:id>', views.addComment, name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views

from django.conf import settings
from django.conf.urls.static import static 

# url pathleri bunun içine yazacağız.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = "index"),   #Sadece '/' olursa hata veriyor. Bu yüzden boş bıraktık ana sayfaya gidebilmek için.
    path('about/',views.about, name = "about"),   # '/' gidilecek url nin sonuna eklenir.
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
  
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class Article(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name = "Yazar") #User tablosundan kullanıcı silindiği zaman buradan da sil 'on_delete'. varolan baika bir tabloyu göstermek istiyorsak Foreignkey kullanıyoruz.
    title = models.CharField(max_length=50, verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name = "Oluşturulma Tarihi")
    article_image = models.FileField(blank = True, null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title  

    class Meta:
        ordering = ['-created_date']   #En son eklenen makale ilk gösteriliyor.

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Makale", related_name= "comments") #Her bir makalemizin birden fazla yorumu olabilir. Commentlerimizi makalelerimize bağlamaya yarıyor.Related name = makalelerimizin yorumlarını almak için bir isim veriyoruz. article.comments diyerek makalenin yorumlarına erişebiliyoruz. Article silindiği zaman yorumlarda silinmesi için on_delete kullandık.
    comment_author = models.CharField(max_length = 50, verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200, verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']  #En son eklenen yorum ilk gösteriliyor.
    

article/forms.py
from django.forms import ModelForm
from .models import Article

class ArticleForm(ModelForm):   #Model Form ile oluşturmak çok kolay.
    class Meta:
        model = Article
        fields = ["title","content","article_image"]  #Title ve content den iki input alanı

article/views.py
from django.shortcuts import redirect, render, HttpResponse, get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment
from django.contrib.auth.decorators import login_required #djangonun içinde gelen decorator. Giriş yapmadan sayfaların gösterilmemesini sağlıyor.

# Create your views here.

def index(request):   
    return render(request,"index.html")


def about(request):
    return render(request,"about.html")


@login_required(login_url="user:login") #Eğer giriş yapmadıysak login sayfasına yönlendir.
def dashboard(request): 
    articles = Article.objects.filter(author = request.user)                      #Kullanıcının makalelerini dashboard da gösterme
    context = {
        "articles" : articles
    }
    return render(request, "dashboard.html",context)


@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None , request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit = False)  #ModelForm dan oluştuğu için formumuz kaydetmesi artık böyle. Save işlemini form.save yapmasın diye commit = False yazdık. Kendimiz yapmak istiyoruz.
        article.author = request.user #Yazar adının atamasını yapıyoruz.
        article.save() #Kendimiz elle kaydediyoruz
        messages.success(request,"Makale Başarıyla Oluşturuldu...")
        return redirect("article:dashboard")
     
    return render(request,"addarticle.html",{"form":form})


def detail(request,id):
    #article = Article.objects.filter(id = id).first() #first demezsek bize liste objesi dönüyor. first diyerek bize ilk elemanı yolluyor.
    article = get_object_or_404(Article, id = id) #istenilen sorgu çalıştırılacak. eğer article yoksa 404 hatası döndürecek.
    comments = article.comments.all()
    
    
    return render(request,"detail.html",{"article" : article,"comments": comments})


@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article, id = id) #Öyle bir article yoksa 404 hatası verir

    form = ArticleForm(request.POST or None, request.FILES or None, instance = article) #instance objesi ile article bilgileri içine gelecek. Bundan emin değilim tekrar bak. Evet instance objesi ile formun içeriği alınıyor.
    if form.is_valid():
        article = form.save(commit = False)  #ModelForm dan oluştuğu için formumuz kaydetmesi artık böyle. Save işlemini form.save yapmasın diye commit = False yazdık. Kendimiz yapmak istiyoruz.
        article.author = request.user #Yazar adının atamasını yapıyoruz.
        article.save() #Kendimiz elle kaydediyoruz
        messages.success(request,"Makale Başarıyla Güncellendi...")
        return redirect("article:dashboard")
  
    return render(request,"update.html", {"form" : form}) # form is valid değilse veya GET request ise burası çalışır. Oluşturduğumuz form gönderilir.


@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article, id = id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi...")
    
    return redirect("article:dashboard") #Article uygulaması altındaki dashboard'a git


def showArticles(request):
    articles = Article.objects.all()   
    return render(request,"articles.html",{"articles" : articles})

def addComment(request,id):
    article = get_object_or_404(Article, id = id)

    if request.method == "POST": #post işlemi gerçekleşince form bilgisinden author ve content bilgilerini alıyoruz. 
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article

        newComment.save()
        
    return redirect(reverse("article:detail", kwargs={"id": id}))

    

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımızda</h3>
<hr>
<p>Merhaba ben Arif Akdeniz. İstanbuk Kültür Üniversitesi Elektrik Elektronik Mühendisliği 4. sınıf öğrencisiyim.</p>

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}  <!-- crispy forms u kullanabilmek için ekledik -->

<div class="row">
  <div class="col-md-6 offset-md-3"> <!-- formu ortalaması için ekledik -->
    <h3>Makale Oluştur</h3>
    <hr>
    <form method = "post", enctype="multipart/form-data"> 
    {% csrf_token %}
    {{form.media}}
    {{form | crispy }}
    <br>

    <button type = "submit" class = "btn btn-danger">Ekle</button>
    </form>
  </div>
</div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}


<div class = "row">
         <div class="col-md-10 offset-md-3">
             <div class="col-lg-8">
                <h3>Makaleler</h3>
                 <hr>
            </div>
        </div>
</div>  

<div class = "row"> 

    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form> <!-- metodumuzu buraya yazmazsak get request olarak gidecek ve ayrıca action olmadığı için yine aynı sayfaya gidecek -->
                {% csrf_token %}
                <input type="text" name = "keyword" class = "input-sm" maxlength="64" placeholder="Ara..">   <!-- Place holder = arama çubuğunda silik yazan yazı -->       
                <button type="submit" class="btn btn-danger ">Ara</button>    
            </form>
        </div>
    </div>

</div>
 


{% if articles %}
    {% for article in articles  %}
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-md-3">
                    <!-- Post Content Column -->
                    <div class="col-lg-8">

                        <!-- Title -->
                        <h2 class="mt-4"><a href = "{% url 'article:detail' article.id %}">{{article.title}}</a></h2>  <!--Başlığın üstüne basıldığında makaleye gidecek-->

                        <!-- Author -->
                        <p class="lead">
                        {{article.author.username}} tarafından yayınlandı.
                        </p>

                        <hr>

                        <!-- Date/Time -->
                        <p>{{article.created_date}}</p>

                        <hr>

                        <!-- Preview Image -->
                        {% if article.article_image %}  <!-- Resim olmayan url lerde sorun çıkmaması için bu if durumunu ekledik -->
                        <a href = "{% url 'article:detail' article.id %}"> <img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""> </a> <!-- resmin üstüne basıldığında makaleye gidecel-->
                        

                        {% endif %}
                        

                        <hr>

                        <!-- Post Content -->
                        <p class = "lead">
                        {{article.content|safe|truncatewords:70}} <!-- ckeditor'de yazıdığımız yazıların normal şekilde görünmesi için kullanıyoruz. Yani html kod olarak görünmemesi için -->
                        <a href = "{% url 'article:detail' article.id %}">Okumaya Devam Et</a>
                        </p> <!-- truncatedwords ile gösterilecek kelime sayısını filtreledik -->

                        <hr>
                        <br>

                        </div> 
                </div>
                    
            <!-- /.row -->
            </div>      
        </div>
    {% endfor %}


{% else %}
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <div class = "alert alert-danger">Makale Bulunamadı...</div>
        </div>
    </div>
{% endif %}




{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
 
<a class= "btn btn-danger" href= "{% url 'article:addarticle' %}">Makale Ekle</a>  <!--Buton yerine link kullandık üzerine link ekledik. -->
<hr>

{% if articles %}
        <table class="table">
        <thead>
            <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles  %}
                <tr>                 <!-- tr etiketi satırları belirler-->
                <th scope="row">{{article.id}}</th>
                <td><a href= "{%url 'article:detail' article.id %}">{{article.title}}</a></td>  <!-- a etiketiyle makale başlığına basılınca makaleye gidilmesi içinmakale başlığına link ekledik. -->
                <td>{{article.author.username}}</td>
                <td>{{article.created_date}}</td>
                <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger"> Güncelle</a></td> <!-- td etiketini unutma -->
                <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger"> Sil</a></td>
                </tr>
            {% endfor %}
            
            {% if articles %}
            
            {% else %}
            {% endif %}

        </tbody>
        </table>

{% else %} <!-- Kullanıcının makalesi bulunmuyorsa tablo gösterilmeyecek  -->
        <div class = "alert alert-danger">Henüz makaleniz bulunmuyor...</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

 <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}  <!-- Resim olmayan url lerde sorun çıkmaması için bu if durumunu ekledik -->
          <img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""> 
         

        {% endif %}
        

        <hr>

        <!-- Post Content -->
        <p class = "lead">
        {{article.content |safe}} <!-- ckeditor'de yazıdığımız yazıların normal şekilde görünmesi için kullanıyoruz. Yani html kod olarak görünmemesi için -->
        </p>

        <hr> 
        <h4>Yorumlar</h4> 
        <hr>
        {% if comments %}
          {% for comment in comments %}
            <div class="media mb-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">{{comment.comment_author}}</h5>
                {{comment.comment_date}} <br>
                {{comment.comment_content}}
              </div>
            </div>

          {% endfor %}
          
        {% else %}
          <div class = "alert alert-danger">Bu makaleye herhangi bir yorum yazılmamış, ilk yorum yapan siz olun! </div>

        {% endif %}
        <div class="card my-4">
          <h5 class="card-header">Yorum Ekle:</h5>
            <div class="card-body">
              <form method= "post" action = "{% url 'article:comment' article.id%}">
                {% csrf_token %}
                <div class="form-group">
                <label for="formGroupExampleInput">İsim:</label>
                <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
                </div>
                <div class="form-group">
                <label for="formGroupExampleInput">Yorum: </label>
                <textarea  name = "comment_content" class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Ekle</button>
              </form>
        </div> 
  </div>
</div>
  
   
   
   
   
   
   
    <!-- /.row -->
    </div>      
  </div>












{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class = "jumbotron text-center">
    <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.</p>
</div>

<p>
        {% if request.user.is_authenticated %}
            Giriş Yapılmış , {{request.user.username}}

        {% else %}
            Giriş Yapılmamış  
        {% endif %}








</p>


{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >


    
    <title>YB Blog</title>
</head>
    <body>
    
            {% include "includes/navbar.html" %}

            <div style = "margin-top : 100px; margin-bottom: 100px;"  class = "container">

                {% if messages %}

                    {% for message in messages %}
                    {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                
                
                    {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>     
            
                    {% endif %}
                
                    {% endfor %}
            
                {% endif %}

    
                {% block body %}
            
            
                {% endblock body %}
        
        
            </div>


        <script src="{% static 'js/jquery-3.2.1.min.js' %}"> </script>
        <script src="{% static 'js/bootstrap.min.js' %}"> </script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}  <!-- crispy forms u kullanabilmek için ekledik -->

<div class="row">
  <div class="col-md-6 offset-md-3"> <!-- formu ortalaması için ekledik -->
    <h3>Giriş Yap</h3>
    <hr>
    <form method = "post">
    {% csrf_token %}

    {{form | crispy }}
    <br>

    <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
 
</form>
  
  </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %} 


<div class="row">
  <div class="col-md-6 offset-md-3">
<h3>Kayıt Olun</h3>
<hr>

<form method = "post"> 
{% csrf_token %}

    {{form | crispy}}     <!--  django da formları gösterebilmek için .as_p dememiz gerekiyor-->
    <br>

    <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>

</form> 

  </div>
</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}  <!-- crispy forms u kullanabilmek için ekledik -->

<div class="row">
  <div class="col-md-6 offset-md-3"> <!-- formu ortalaması için ekledik -->
    <h3>Makale Güncelle</h3>
    <hr>
    <form method = "post", enctype="multipart/form-data"> 
    {% csrf_token %}
    {{form.media}}
    {{form | crispy }} <!-- formlarımızı güzelleştirmek için -->
    <br>

    <button type = "submit" class = "btn btn-danger">Güncelle</button>
    </form>
  </div>
</div>


{% endblock body %}